data:
  local_dir: data
  file_name: data.zip
  unzip_data: data
  BAD_DATA_DIR: bad_data
  PARENT_DIR: data\PetImages
  model_dir: model
  init_model_file: init_model.h5

params:
  img_shape: [180, 180, 3]
  learning_rate: 0.01
  loss: "sparse_categorical_crossentropy"
  metrics: ["accuracy"]
